name: "Uppercase"
description: "Convert text to uppercase"
author: "yu-fukunaga"
inputs:
  text:
    description: "Text to convert to uppercase"
    required: true
outputs:
  uppercase-text:
    description: "Text converted to uppercase"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.text }}
branding:
  icon: "chevron-up"
  color: "blue"
